---
- name: Server Availability Check
  ansible.windows.win_ping:
  register: ping_result

- name: Record unreachable servers
  debug:
    var: inventory_hostname
  when: ping_result.failed

- name: Building Availability Report
  ansible.windows.win_template:
    src: connectivity_report.j2
    dest: C:\Availability_report_{{ ansible_date_time.iso8601 }}.txt
  delegate_to: DC