---
- name: Server Availability Check
  ansible.windows.win_ping:
  register: ping_result
-block:
  - name: building results
    set_fact:
      ping_results: "{{ ansible_play_hosts_all|difference(ansible_play_hosts) }}"
   
  - name: Building Availability Report
    ansible.windows.win_template:
      src: connectivity_report.j2
      dest: C:\Availability_report.txt
delegate_to: DC
run_once: yes