---
- name: Server Availability Check
  ansible.windows.win_ping:
  register: ping_result

- name: building results
  set_fact:
    ping_results: "{{ ansible_play_hosts_all|difference(ansible_play_hosts) }}"

- name: Building Availability Report
  debug:
    var: ping_results
  run_once: yes