---
- name: Server Availability Check
  ansible.windows.win_ping:
  register: ping_result
- name: building results
  set_fact:
    ping_results: "{{ ping_results | default([]) + 'host': inventory_hostname, 'ping':'pong' if ping_result is defined else 'unreacheable' }}"

- name: Building Availability Report
  ansible.windows.win_template:
    src: connectivity_report.j2
    dest: C:\Availability_report.txt
  delegate_to: DC
  run_once: yes