---
- name: Gather Windows facts
  ansible.windows.win_stat:
    path: C:\Windows\System32
  register: win_facts

- name: Get Windows version from registry
  ansible.windows.win_shell: |
    reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v "ProductName"
  register: win_version

- name: Determine Windows Server version
  set_fact:
    windows_server_version: >
      {% if '2019' in win_version.stdout %}
        Windows Server 2019
      {% elif '2016' in win_version.stdout %}
        Windows Server 2016
      {% elif '2012' in win_version.stdout %}
        Windows Server 2012
      {% else %}
        Unknown version
      {% endif %}

- name: Display Windows Server version
  ansible.builtin.debug:
    msg: "The Windows Server version is {{ windows_server_version }}"
