---
- name: Manage AD users and group memberships
  hosts: all
  gather_facts: no
  tasks:

    - name: Define source and task accounts
      set_fact:
        source_accounts: ["SSSS", "SSSS_a", "SSSS_ca", "SSSS_da"]
        task_accounts: ["TTTT", "TTTT_a", "TTTT_ca", "TTTT_da"]

    - name: Check if source_param accounts exist and retrieve their OU
      win_shell: |
        $account = "{{ item }}"
        $user = Get-ADUser -Identity $account -ErrorAction SilentlyContinue
        if ($null -ne $user) {
          $ou = ($user.DistinguishedName -split ',')[1..($user.DistinguishedName.Length - 1)] -join ','
          Write-Host "EXISTS $ou"
        } else {
          Write-Host "MISSING"
        }
      register: account_check
      loop: "{{ source_accounts }}"
      changed_when: false

    - name: Filter out non-existent source accounts and retrieve OUs
      set_fact:
        existing_accounts: "{{ existing_accounts | default({}) | combine({item.item: item.stdout.split(' ')[1]}) }}"
      when: item.stdout.startswith('EXISTS')
      loop: "{{ account_check.results }}"

    - name: Create task_param accounts in the same OU as the source_param accounts
      win_shell: |
        $taskAccount = "{{ item.key | regex_replace('SSSS', 'TTTT') }}"
        New-ADUser -Name $taskAccount -UserPrincipalName "$taskAccount@domain.com" -SamAccountName $taskAccount -Path "{{ item.value }}" -AccountPassword (ConvertTo-SecureString "B@nk0fC@N890" -AsPlainText -Force) -Enabled $true
      loop: "{{ existing_accounts | dict2items }}"

    - name: Add task_param accounts to the same groups as the source_param accounts
      win_shell: |
        $sourceAccount = "{{ item.key }}"
        $taskAccount = "{{ item.key | regex_replace('SSSS', 'TTTT') }}"
        $groups = Get-ADUser -Identity $sourceAccount -Properties MemberOf | Select-Object -ExpandProperty MemberOf
        foreach ($group in $groups) {
          Add-ADGroupMember -Identity $group -Members $taskAccount
        }
      when: item.key in existing_accounts.keys()  # Ensure the source account exists
      loop: "{{ existing_accounts | dict2items }}"
