---
- name: Configure Windows Defender exclusions and schedule
  hosts: all
  vars:
    excluded_folders: # List of folders to exclude (provided as parameters)
      - "C:\\path\\to\\folder1"
      - "D:\\path\\to\\folder2"
    exclusion_schedule: "Mon-Fri" # Schedule for exclusions (Monday to Friday)

  tasks:
    - name: Add folders to Windows Defender exclusions
      win_shell: |
        Add-MpPreference -ExclusionPath "{{ item }}"
      loop: "{{ excluded_folders }}"
      when: >
        (ansible_date_time.weekday == 'Monday' and 'Mon' in exclusion_schedule) or
        (ansible_date_time.weekday == 'Tuesday' and 'Tue' in exclusion_schedule) or
        (ansible_date_time.weekday == 'Wednesday' and 'Wed' in exclusion_schedule) or
        (ansible_date_time.weekday == 'Thursday' and 'Thu' in exclusion_schedule) or
        (ansible_date_time.weekday == 'Friday' and 'Fri' in exclusion_schedule)

    - name: Remove folders from Windows Defender exclusions on weekends
      win_shell: |
        Remove-MpPreference -ExclusionPath "{{ item }}"
      loop: "{{ excluded_folders }}"
      when: >
        (ansible_date_time.weekday == 'Saturday' or ansible_date_time.weekday == 'Sunday')

    - name: Ensure Windows Defender service is running
      win_service:
        name: WinDefend
        state: started
