---
- name: Check Failover Clustering status on all servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Check Failover Clustering installation status
      win_shell: |
        Get-WindowsFeature -Name Failover-Clustering | Select-Object -ExpandProperty InstallState
      register: clustering_status

    - name: Determine installation status of Failover Clustering
      set_fact:
        failover_clustering_installed: "{{ clustering_status.stdout.strip() == 'Installed' }}"

    - name: Add server to clustering report
      ansible.builtin.local_action:
        module: set_fact
        args:
          clustering_report_global: "{{ ansible_local.clustering_report_global | default([]) + [{'server': inventory_hostname, 'status': 'Installed' if failover_clustering_installed else 'Not Installed'}] }}"
      run_once: true
      delegate_to: localhost

- name: Save clustering report to VM01
  hosts: VM01
  gather_facts: no
  tasks:
    - name: Create clustering report CSV
      copy:
        content: |
          Server,Status
          {% for item in clustering_report_global %}
          {{ item.server }},{{ item.status }}
          {% endfor %}
        dest: C:\clustering_report.csv
      vars:
        clustering_report_global: "{{ hostvars['localhost'].clustering_report_global }}"