---
- name: Check SCCM Agent and Generate Report
  hosts: all
  gather_facts: no
  tasks:
    - name: Check if SCCM agent is present
      win_shell: |
        $serviceName = "ccmexec"
        $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
        if ($service) {
            Write-Output "Present"
        } else {
            Write-Output "Absent"
        }
      register: sccm_status
      ignore_errors: true

    - name: Record SCCM agent status per host
      set_fact:
        sccm_status_fact: "{{ sccm_status.stdout | default('Unreachable') | trim }}"
      when: sccm_status is defined and sccm_status.stdout is defined

- name: Generate SCCM Agent Summary
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Initialize summary data
      set_fact:
        total_reachable: 0
        total_with_agent: 0
        total_without_agent: 0
        total_unreachable: 0
        servers_without_agent: []
        servers_unreachable: []

    - name: Process SCCM statuses from all servers
      set_fact:
        total_reachable: "{{ total_reachable | int + (1 if hostvars[item].sccm_status_fact != 'Unreachable' else 0) }}"
        total_with_agent: "{{ total_with_agent | int + (1 if hostvars[item].sccm_status_fact == 'Present' else 0) }}"
        total_without_agent: "{{ total_without_agent | int + (1 if hostvars[item].sccm_status_fact == 'Absent' else 0) }}"
        total_unreachable: "{{ total_unreachable | int + (1 if hostvars[item].sccm_status_fact == 'Unreachable' else 0) }}"
        servers_without_agent: "{{ servers_without_agent + ([item] if hostvars[item].sccm_status_fact == 'Absent' else []) }}"
        servers_unreachable: "{{ servers_unreachable + ([item] if hostvars[item].sccm_status_fact == 'Unreachable' else []) }}"
      with_items: "{{ groups['all'] }}"
      loop_control:
        label: "{{ item }}"

    - name: Prepare report content
      set_fact:
        sccm_report_content: |
          SCCM Agent Check Report
          ========================
          Total Reachable Servers: {{ total_reachable }}
          Servers with SCCM Agent: {{ total_with_agent }}
          Servers without SCCM Agent: {{ total_without_agent }}
          Unreachable Servers: {{ total_unreachable }}

          List of Servers without SCCM Agent:
          -----------------------------------
          {% for server in servers_without_agent %}
          {{ server }}
          {% endfor %}

          List of Unreachable Servers:
          ----------------------------
          {% for server in servers_unreachable %}
          {{ server }}
          {% endfor %}

    - name: Write summary report on VM01
      win_copy:
        content: "{{ sccm_report_content }}"
        dest: C:\sccm_summary.txt
      delegate_to: "{{ report_server }}"
      run_once: true
