---
- name: Check Windows Failover Cluster Role
  hosts: all
  gather_facts: no
  tasks:
    - name: Check if Failover-Clustering feature is installed
      win_feature:
        name: Failover-Clustering
        state: present
      register: cluster_role_status
      check_mode: yes

    - name: Determine Failover-Clustering installation status
      set_fact:
        cluster_installed: >
          {{ cluster_role_status.feature_result | selectattr('display_name', 'search', 'Failover Clustering') | map(attribute='success') | list | first | default(false) }}

    - name: Display Failover-Clustering feature status
      debug:
        msg: >
          Failover-Clustering feature is
          {% if cluster_installed %}
            installed
          {% else %}
            not installed
          {% endif %}
          on {{ inventory_hostname }}.