---
- name: Check SCCM Agent and Generate Report
  hosts: all
  gather_facts: no
  tasks:
    - name: Check if SCCM agent is present
      win_shell: |
        $serviceName = "ccmexec"
        $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
        if ($service) {
            Write-Output "Present"
        } else {
            Write-Output "Absent"
        }
      register: sccm_status
      ignore_errors: true

    - name: Record SCCM agent status per host
      set_fact:
        sccm_status_fact: "{{ sccm_status.stdout | default('Unreachable') | trim }}"

- name: Generate SCCM Agent Summary
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Collect results from all servers
      set_fact:
        sccm_results: >
          {{
            groups['all'] | map('extract', hostvars, 'sccm_status_fact') | list
          }}
        servers_with_agent: >
          {{
            groups['all'] | selectattr("sccm_status_fact", "equalto", "Present") | list
          }}
        servers_without_agent: >
          {{
            groups['all'] | selectattr("sccm_status_fact", "equalto", "Absent") | list
          }}
        unreachable_servers: >
          {{
            groups['all'] | selectattr("sccm_status_fact", "equalto", "Unreachable") | list
          }}

    - name: Prepare report content
      set_fact:
        sccm_report_content: |
          SCCM Agent Check Report
          ========================
          Total Reachable Servers: {{ sccm_results | difference(unreachable_servers) | length }}
          Servers with SCCM Agent: {{ servers_with_agent | length }}
          Servers without SCCM Agent: {{ servers_without_agent | length }}
          Unreachable Servers: {{ unreachable_servers | length }}

          List of Servers without SCCM Agent:
          -----------------------------------
          {% for server in servers_without_agent %}
          {{ server }}
          {% endfor %}

          List of Unreachable Servers:
          ----------------------------
          {% for server in unreachable_servers %}
          {{ server }}
          {% endfor %}

    - name: Write summary report on VM01
      win_copy:
        content: "{{ sccm_report_content }}"
        dest: C:\SCCM_Report\sccm_summary.txt
      delegate_to: VM01
      run_once: true
