---
- name: Check Windows Failover Cluster Feature
  hosts: all
  gather_facts: no
  tasks:
    - name: Check Failover Clustering feature status
      win_feature:
        name: Failover-Clustering
        state: present
      register: cluster_feature_status
      check_mode: yes  # Avoids making changes

    - name: Display raw output of win_feature
      debug:
        var: cluster_feature_status

    - name: Determine if Failover Clustering is installed
      set_fact:
        failover_clustering_installed: >
          {{ cluster_feature_status.feature_result | selectattr('name', 'equalto', 'Failover-Clustering') | map(attribute='install_state') | list | first | default('Not Installed') == 'Installed' }}

    - name: Display Failover Clustering installation status
      debug:
        msg: >
          Failover Clustering feature is
          {% if failover_clustering_installed %}
            installed
          {% else %}
            not installed
          {% endif %}
          on {{ inventory_hostname }}.