---
- name: Check SCCM Agent Presence on Windows Servers
  hosts: all
  vars:
    no_agent_list: []  # List for servers without SCCM agent
    reachable_servers: []  # List for servers successfully reached

  tasks:
    - name: Run PowerShell script to check SCCM agent
      win_shell: |
        $serviceName = "ccmexec"
        $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
        if ($service) {
            Write-Output "Present"
        } else {
            Write-Output "Absent"
        }
      register: sccm_status
      ignore_errors: true

    - name: Add reachable servers to a list
      set_fact:
        reachable_servers: "{{ reachable_servers + [inventory_hostname] }}"
      when: sccm_status.stdout is defined and sccm_status.stdout.strip() in ['Present', 'Absent']

    - name: Add servers without SCCM agent
      set_fact:
        no_agent_list: "{{ no_agent_list + [inventory_hostname] }}"
      when: sccm_status.stdout is defined and sccm_status.stdout.strip() == 'Absent'

    - name: Add unreachable servers to no_agent_list
      set_fact:
        no_agent_list: "{{ no_agent_list + [inventory_hostname] }}"
      when: sccm_status is not defined or sccm_status.stdout is not defined

    - name: Create report directory on VM01
      win_file:
        path: C:\SCCM_Report
        state: directory
      delegate_to: VM01
      run_once: true

    - name: Write summary report on Report VM
      win_shell: |
        $summaryPath = "C:\SCCM_Report\sccm_summary.txt"
        $totalReachable = {{ reachable_servers | length }}
        $totalWithAgent = {{ (reachable_servers | difference(no_agent_list)) | length }}
        $totalWithoutAgent = {{ no_agent_list | length }}

        $serversWithoutAgent = @"
        {% for server in no_agent_list %}
        {{ server }}
        {% endfor %}
        "@

        $reportContent = @"
        SCCM Agent Check Report
        ========================

        Total Reachable Servers Checked: $totalReachable
        Servers with SCCM Agent: $totalWithAgent
        Servers without SCCM Agent: $totalWithoutAgent

        List of Servers without SCCM Agent:
        -----------------------------------
        $serversWithoutAgent
        "@

        $reportContent | Out-File -FilePath $summaryPath
      delegate_to: VM01
      run_once: true
