---
- name: Verify Failover Clustering Installation
  hosts: all
  gather_facts: no
  tasks:
    - name: Check Failover Clustering installation status
      win_shell: |
        Get-WindowsFeature -Name Failover-Clustering | Select-Object -ExpandProperty InstallState
      register: clustering_status

    - name: Display raw output from PowerShell
      debug:
        var: clustering_status.stdout

    - name: Determine installation status of Failover Clustering
      set_fact:
        failover_clustering_installed: "{{ clustering_status.stdout.strip() == 'Installed' }}"

    - name: Display Failover Clustering installation status
      debug:
        msg: >
          Failover Clustering feature is
          {% if failover_clustering_installed %}
            installed
          {% else %}
            not installed
          {% endif %}
          on {{ inventory_hostname }}.