---
- name: Check Failover Clustering status and generate CSV
  hosts: all
  gather_facts: no
  tasks:
    - name: Check Failover Clustering installation status
      win_shell: |
        Get-WindowsFeature -Name Failover-Clustering | Select-Object -ExpandProperty InstallState
      register: clustering_status

    - name: Determine installation status of Failover Clustering
      set_fact:
        failover_clustering_installed: "{{ clustering_status.stdout.strip() == 'Installed' }}"

    - name: Aggregate clustering report
      delegate_to: VM01
      ansible.builtin.lineinfile:
        path: C:\clustering_report.csv
        line: "{{ inventory_hostname }},{{ 'Installed' if failover_clustering_installed else 'Not Installed' }}"
        create: yes
      run_once: "{{ inventory_hostname == groups['windows_servers'][0] }}"
      when: clustering_status is defined

    - name: Ensure CSV header exists
      delegate_to: VM01
      ansible.builtin.lineinfile:
        path: C:\clustering_report.csv
        line: "Server,Status"
        create: yes
        insertbefore: BOF
      run_once: true