---
- name: Check Failover Clustering status and generate CSV for Installed Servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Check Failover Clustering installation status
      win_shell: |
        Get-WindowsFeature -Name Failover-Clustering | Select-Object -ExpandProperty InstallState
      register: clustering_status

    - name: Determine installation status of Failover Clustering
      set_fact:
        failover_clustering_installed: "{{ clustering_status.stdout.strip() == 'Installed' }}"

    - name: Append server to CSV if feature is installed
      win_shell: |
        Add-Content -Path "C:\clustering_report.csv" -Value "{{ inventory_hostname }},Installed"
      delegate_to: VM01
      when: failover_clustering_installed

    - name: Ensure CSV header exists (only for Installed Servers)
      win_shell: |
        if (!(Test-Path -Path "C:\clustering_report.csv")) {
            Add-Content -Path "C:\clustering_report.csv" -Value "Server,Status"
        }
      delegate_to: VM01
      run_once: true