---
- hosts: all
  tasks:
    - name: Gather facts
      setup:
        filter:
          - ansible_hostname

    - name: Transfer file from win-01 to other hosts
      win_copy:
        src: C:\myshared\file2copy.txt
        dest: C:\
        remote_src: yes
      delegate_to: NSW-01
      when: inventory_hostname != 'NSW-01'