---
- hosts: all
gather_facts: false
ignore_errors: true
tasks:
- name: Deleting previously copied files
  ansible.windows.win_powershell:
    script: |
      Remove-Item -Path "C:\file2copy"

- name: Copyinf file to windows hosts
  ansible.windows.win_powershell:
    script: |
      Copy-Item -Path "\\DC.nshsoft.local\file2copy".txt" -Destination "C:\"