---
- name: Windows Server Disk Health Check
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather disk facts
      win_disk_facts:
      register: disk_facts

    - name: Determine disks with 80% or more usage
      set_fact:
        high_usage_disks: "{{ high_usage_disks | default([]) + [item.key] }}"
      loop: "{{ disk_facts.ansible_facts.disks | dict2items }}"
      when: 'item.value.size_used / item.value.size_total >= 0.8'

    - name: Display disks with 80% or more usage in tabular form
      debug:
        msg: "{{ inventory_hostname }}: {{ high_usage_disks }}"
      when: high_usage_disks | default([]) | length > 0

    - name: Find the 15 largest files on high usage disks
      win_shell: |
        Get-ChildItem -Path '{{ item }}' -Recurse -File | 
        Sort-Object Length -Descending | 
        Select-Object -First 15 | 
        Select-Object FullName, @{Name="SizeInMB";Expression={$_.Length / 1MB}} | 
        Format-Table -AutoSize | 
        Out-String -Width 4096
      register: largest_files
      loop: "{{ high_usage_disks }}"
      ignore_errors: yes
      when: high_usage_disks | default([]) | length > 0

    - name: Create a text file on C: drive listing the 15 largest files
      win_lineinfile:
        path: C:\disk_health_check\largest_files_{{ inventory_hostname }}.txt
        line: "{{ item.stdout }}"
        create: yes
      loop: "{{ largest_files.results }}"
      when: largest_files.results | length > 0
