---
- name: Windows Disk Health Check
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather facts for date and time
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!any'
          - 'date_time'

    - name: Get C drive disk information
      ansible.windows.win_shell: |
        Get-PSDrive C | Select-Object @{Name='Used(GB)';Expression={[math]::Round(($_.Used / 1GB), 2)}},@{Name='Free(GB)';Expression={[math]::Round(($_.Free / 1GB), 2)}},@{Name='TotalSize(GB)';Expression={[math]::Round((($_.Used + $_.Free) / 1GB), 2)}},@{Name='PercentFree';Expression={if($_.Used -ne 0) { [math]::Round(($_.Free / ($_.Used + $_.Free) * 100), 2)} else {0}}} | ConvertTo-Json
      register: disk_info

    - name: Check if C drive usage is above 80%
      ansible.builtin.set_fact:
        high_usage: "{{ (disk_info.stdout | from_json).PercentFree | float < 45.0 }}"

    - name: Create a folder with the current date
      ansible.windows.win_file:
        path: "\\\\DC\\MyShared\\{{ ansible_date_time.date }}"
        state: directory
      when: high_usage

    - name: Find files over 250MB on C drive
      ansible.windows.win_shell: |
        Get-ChildItem C:\ -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.Length -gt 262144000 } | Select-Object FullName, @{Name="SizeInGB";Expression={"{0:N2}" -f ($_.Length / 1GB)}}
      register: large_files
      when: high_usage
      ignore_errors: yes

    - name: Generate report if usage is more than 80%
      ansible.builtin.template:
        src: disk_report.j2
        dest: "\\\\DC\\MyShared\\{{ ansible_date_time.date }}\\{{ inventory_hostname }}_disk_report.txt"
      when: high_usage
