- hosts: all
  tasks:
    - name: Get disk usage facts  
      win_disk_facts:

    - name: Check disk usage
      win_shell: | 
        $threshold = 20
        $disks = Get-WmiObject Win32_LogicalDisk | Where-Object {$_.DriveType -eq "3"}  
        $results = @()
        foreach ($disk in $disks) {
          $percent = [int]($disk.FreeSpace/$disk.Size*100)   
          if ($percent -le $threshold) {
            $props = @{
              Device = $disk.DeviceID
              PercentFree = $percent 
            }
            $results += New-Object -TypeName PSObject -Property $props
          }
        }
        $results | Format-Table Device,PercentFree -AutoSize
      register: disk_space

    - name: Create file with 15 largest files 
      win_shell: |
        $threshold = 20
        $count = 15
        $results = @()
        Get-WmiObject Win32_LogicalDisk | ForEach-Object {
          $deviceId = $_.DeviceID  
          $percent = [int]($_.FreeSpace/$_.Size*100)
          if ($percent -le $threshold) {
            $largeFiles = Get-ChildItem -Path $deviceId -Recurse -File | Sort-Object -Property Length -Descending | Select-Object -First $count FullName,Length,LastWriteTime
            $results += $largeFiles
          }
        }
        $results | Out-File -FilePath C:\largest-files.txt
      when: disk_space.stdout_lines | length > 0