- hosts: "{{hostname}}"
  gather_facts: no

  tasks:
    - name: Get C drive space facts
      win_disk_facts:
        drive: c

    - name: Display disk space
      debug:
        msg: "Total - {{ ansible_disks['c']['size']|filesizeformat('%0.1f GB') }}, Used - {{ ansible_disks['c']['used']|filesizeformat('%0.1f GB') }}, Free - {{ ansible_disks['c']['free']|filesizeformat('%0.1f GB') }}"