---
- name: Check Disk Usage on Windows Server
  hosts: Winds
  gather_facts: true
  tasks:
    - name: Get Disk Usage
      ansible.windows.win_powershell:
        script: |
          $disk = Get-WmiObject Win32_LogicalDisk -Filter "DeviceID='C:'" | Select-Object Size, FreeSpace
          $total = $disk.Size
          $free = $disk.FreeSpace
          $usage = (($total - $free) / $total) * 100
          $report = New-Object PSObject -Property @{
            ServerName = $env:COMPUTERNAME
            DiskUsage = $usage
          }
          $report
      register: disk_usage_result

    - name: Display Disk Usage Report
      debug:
        var: disk_usage_result.stdout_lines

    - name: Create Report File
      ansible.windows.win_powershell:
        script: |
          $report = "{{ disk_usage_result.stdout }}"
          if ($report.DiskUsage -lt 80) {
            $status = "Healthy"
          } else {
            $status = "Action Needed"
          }
          $reportString = "Server Name: $($report.ServerName)`r`nDisk Usage: $($report.DiskUsage)%`r`nStatus: $status"
          Set-Content -Path "C:\Disk_Report.txt" -Value $reportString
      delegate_to: DC
