---
- hosts: all
  collesctions:
  - community.windows
  - community.general
  - chocolatey.chocolatey
  - microsoft.ad
  tasks:
  - name: Sending an email using Ansible
    community.general.mail:
      host: smtp.gmail.com
      port: 587
      username: nangsonghermann@gmail.com
      password: "{{ p }}"
      to: Hermann Gael <hermanngael47@gmail.com>
      subject: Email By Ansible
      body: System {{ ansible_hostname }} has been successfully provisioned.
    #delegate_to: DC.nshsoft.local
    run_once: yes

