---
- hosts: localhost
  tasks:
  - name: Sending an email using Ansible
    community.general.mail:
      host: smtp.gmail.com
      port: 587
      username: nangsonghermann@gmail.com
      password: "{{ p }}"
      to: hermanngael47@gmail.com
      subject: Email By Ansible
      body: Test successful
    delegate_to: DC
    run_once: yes