---
- hosts: windows
  gather_facts: no

  tasks:
    - name: Install 7zip
      win_chocolatey:
        name: 7zip
        state: present

    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present