---
- hosts: all
  gather_facts: false
  tasks:
  - name: Ensure OU is present & protected
    microsoft.ad.ou:
      name: AnsibleFest01
      path: OU=NSHSOFT,DC=nshsoft,DC=local
      state: present
    delegate_to: DC
    run_once: yes