---
- name: Creating OU in Active Directory
  hosts: all
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: OU creation on Directory
      ansible.windows.win_powershell:
        script: |
          # Import the Active Directory module
          Import-Module ActiveDirectory

          # Define the name of the OU to create
          $ouName = "NewOU100"

          # Define the distinguished name of the parent container where you want to create the OU
          $parentContainer = "OU=Computers,OU=NSHSOFT,DC=nshsoft,DC=local"

          # Create the OU
          New-ADOrganizationalUnit -Name $ouName -Path $parentContainer