---
- name: Testing Connectivity
  hosts: Winds
  gather_facts: false 
  ignore_errors: true 
  tasks:
    - name: Connectivity Test - Ping
      ansible.windows.win_ping:
      register: ping_Result
 