---
- name: Testing Connectivity
  hosts: Winds
  gather_facts: false  
  vars:
    connection_results: []
  tasks:
    - name: Connectivity Test - Ping
      ping:
      register: ping_result  # Store the result for later

    - name: Determine Host Status
      set_fact:
        host_status: "NO-RESPONSIVE"  # Default to unresponsive
      when: ping_result.unreachable == true

    - name: Determine Host Status (Responsive)
      set_fact:
        host_status: "RESPONSIVE"
      when: ping_result.unreachable == false

    - name: Display Host Status
      debug:
        msg: "Host {{ inventory_hostname }} Status: {{ host_status }}"