---
- name: Test Kerberos Authentication
  hosts: windows_Host
  gather_facts: false
  tasks:

    - name: Connectivity Test - Ping
      ansible.windows.win_ping:
      register: ping_Result

