---
- name: Connectivity Test
  hosts: Winds
  gather_facts: false

  tasks:
    - name: Connectivity Test - Ping
      ping:

    - name: Capturing ping global results
      set_fact:
        connection_results: "{{ connection_results | default([]) + [{'Host': inventory_hostname, 'Status': 'RESPONSIVE'}] }}"
      when: "'unreachable' not in hostvars[inventory_hostname]"

    - name: Set 'NO-RESPONSIVE' status for unreachable hosts
      set_fact:
        connection_results: "{{ connection_results | default([]) + [{'Host': item, 'Status': 'NO-RESPONSIVE'}] }}"
      with_items: "{{ groups['Winds'] }}"
      when: "'unreachable' in hostvars[item]"

    - name: Display Ping result
      debug:
        var: connection_results
