---
- name: Testing Connectivity
  hosts: Winds
  gather_facts: false  
  vars:
    connection_results: []
  tasks:
    - name: Connectivity Test - Ping
      ansible.windows.win_ping:
      register: ping_Result

    - name: Capturing ping global results
      set_fact:
        connection_results: "{{ connection_results + [{ 'Host': inventory_hostname, 'Status': 'RESPONSIVE' if ping_Result.ping =='pong' else 'NOT-RESPONSIVE' }] }}"

    - name: Display Ping result
      debug:
        var: connection_results