---
- name: Power Off Windows Server
  hosts: "{{ myhost  }}"
  tasks:
    - name: Shut down Windows host
      ansible.windows.win_shutdown:
        shutdown_timeout: 60 # Time to wait before shutting down (seconds)

    - name: Wait for server to go offline
      ansible.builtin.wait_for_disconnection:
        delay: 15 # Delay before starting to check (seconds)
        timeout: 300 # How long to wait for disconnection (seconds)
