---
- hosts: "{{ myhost }}"
  gather_facts: no

  tasks:
    - name: Power off Windows server
      win_command: shutdown.exe /s /t 60 /c "Powering off server"
      async: 60
      poll: 0
      become: yes
      become_method: runas
      become_user: SYSTEM
      ignore_errors: yes

    - name: Wait for the Windows server to power off
      wait_for:
        host: "{{ ansible_host }}"
        port: 5986
        state: stopped
        timeout: 120
      delegate_to: localhost
