---
- hosts: all
  gather_facts: no
  vars: 
    x: 35
  tasks:
  - set_stats:
      data:
        myvar: "{{ x }}"

  - debug:
      var: x  

  - name: send email
    mail:
      hosts: mail.htttckumba.com
      port: 465
      username: nangsonghermann@htttckumba.com
      password: "{{ mail_pass }}"
      from: nangsonghermann@htttckumba.com
      to: nangsonghermann@hmail.com
      subject: "My Email test in AWX"
      body: "I pray my test works"
      attach:
      secure: starttls
    