- name: Install Python on Windows servers
  hosts: all
  collections:
    - ansible.windows
  gather_facts: false
  tasks:
    - name: Install latest version of Python
      win_chocolatey:
        name: python
        state: latest

