---
- name: Schedule a reboot of a Windows server
  hosts: "{{ hostname }}"
  gather_facts: no
  vars:
    hours: "{{hours}}"
   
  tasks:
    - name: Calculate delay in seconds
      set_fact:
        delay_seconds: "{{ hours | int * 3600 }}"

    - name: Wait for the specified duration
      pause:
        seconds: "{{ delay_seconds }}"
      when: delay_seconds |int > 0

    - name: Reboot the server
      win_reboot:
        msg: "Scheduled reboot by Ansible"
        pre_reboot_delay: 0
        post_reboot_delay: 300
      when: delay_seconds|int > 0

    - name: Notify that no reboot is scheduled
      debug:
        msg: "No reboot scheduled as the duration is not greater than 0."
      when: delay_seconds | int <= 0
