---
- name: Reboot Windows Server
  hosts: "{{ myhost }}"
  tasks:
    - name: Reboot Windows host
      ansible.windows.win_reboot:
        shutdown_timeout: 60
        reboot_timeout: 300
      register: reboot_result

    - name: Wait for server to come back online
      ansible.builtin.wait_for_connection:
        delay: 15
        timeout: 300
        sleep: 15
      when: reboot_result.changed
