---
- name: Schedule a reboot of a Windows server
  hosts: "{{ hostname }}"
  gather_facts: no
  vars:
    hours: "{{hours}}"
   
  tasks:
    - name: Calculate the reboot time
      set_fact:
        reboot_time: "{{ '%Y-%m-%d %H:%M:%S' | strftime((ansible_date_time.epoch | int) + (hours | int * 3600)) }}"

    - name: Schedule the reboot task
      win_scheduled_task:
        name: "ScheduledReboot"
        description: "Ansible scheduled reboot"
        actions:
        - path: "C:\\Windows\\System32\\shutdown.exe"
          arguments: "/r /t 0"
        triggers:
        - type: "once"
          start_boundary: "{{ reboot_time }}"
        state: present
        enabled: yes

    - name: Confirm scheduled reboot
      debug:
        msg: "Reboot scheduled at {{ reboot_time }}"
