---
- name: Schedule a reboot of a Windows server
  hosts: "{{ hostname }}"
  gather_facts: no
 
  tasks:
    - name: Rebooting {{ hostname }} 
      win_reboot:
        reboot_timeout: 120
      ignore_errors: yes
      async: 0
      poll: 0

    - name: Wait for Windows Server to come back online
      wait_for_connection:
        timeout: 600

