---
- name: Install packages on Windows servers using Chocolatey
  hosts: "{{ myhost }}"
  # vars:
  #   chocolatey_packages: "{{ packages.split(',') }}"

  tasks:
    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install packages using Chocolatey
      win_chocolatey:
        name: "{{ item }}"
        state: present
      loop: "{{ chocolatey_packages }}"
