---
- name: Install software on Windows servers
  hosts: "{{ myhost }}"
  vars:
    shared_folder: "\\\\NSH-DC01\\MyShared"
  tasks:
    - name: Install MSI package
      ansible.windows.win_package:
        path: "{{ shared_folder }}\\{{ software_name }}.msi"
        state: present
      when: software_name is ansible.builtin.match(".*\\.msi$")

    - name: Install EXE package
      ansible.windows.win_package:
        path: "{{ shared_folder }}\\{{ software_name }}.exe"
        product_id: "{{ software_name }}"
        arguments: /q /norestart
      when: software_name is ansible.builtin.match(".*\\.exe$")
