- hosts: "{{ hostnames }}"
  tasks:
   # 7-Zip exe doesn't use a guid for the Product ID
    - name: Install 7zip from a network share with specific credentials
      ansible.windows.win_package:
        path: \\DC\MyFiles\7z2401-x64.exe
        product_id: 7-Zip
        arguments: /S
        state: present
  become: true
  become_method: runas
  become_flags: logon_type=new_credential logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ username }}"
    ansible_become_password: "{{ password }}"