---
- name: Generate an HTML report from jinja template
  hosts: Winds
  gather_facts: true
  vars:
    #random settings
    csv_path: C:\report.csv
    headers: Hostname,Dusage
 
  tasks:
  - name: get disk usage
    ansible.windows.win_powershell:
      script: |
        $disk = Get-WmiObject Win32_LogicalDisk -Filter "DeviceID='C:'" | Select-Object Size, FreeSpace
        $total = $disk.Size
        $free = $disk.FreeSpace
        $usage = [math]::Round((($total - $free) / $total) * 100, 2)
        $usage
    register: disk_result
 
  - name: Touch a file (creates if not present, updates modification time if present)
    win_file:
      path: C:\report.csv
      state: touch
    delegate_to: DC
    run_once: yes

  - name: Save CSV headers
    ansible.builtin.lineinfile:
      dest: "{{ csv_path }}"
      line: "{{ headers }}"
      create: true
      state: present
    delegate_to: DC
    run_once: true
 
  - name: Build out CSV file
    ansible.builtin.lineinfile:
      dest: "{{ csv_path }}"
      line: "{{ inventory_hostname }},{{ ansible_distribution_version }}"
      create: true
      state: present
    delegate_to: DC
 

 
