---
- name: Collect uptime information from all Windows servers
  hosts: all
  gather_facts: no
  vars:
    report_path: "C:\\windows_uptime_report_consolidated.csv"
   
  tasks:
    - name: Get system uptime using PowerShell
      ansible.windows.win_shell: |
        $os = Get-WmiObject -Class Win32_OperatingSystem
        $lastBootTime = $os.ConvertToDateTime($os.LastBootUpTime)
        $uptime = (Get-Date) - $lastBootTime
        [PSCustomObject]@{
            ServerName = $env:COMPUTERNAME
            LastBootTime = $lastBootTime
            UptimeDays = $uptime.Days
        } | ConvertTo-Json
      register: uptime_info

    - name: Collect uptime information from all servers
      set_fact:
        server_uptime: "{{ uptime_info.stdout | from_json }}"

    - name: Get Windows version from registry
      ansible.windows.win_shell: |
        reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v "ProductName"
      register: win_version

    - name: Determine Windows Server version
      set_fact:
        windows_server_version: >
          {% if '2022' in win_version.stdout %}
            Windows Server 2022
          {% elif '2019' in win_version.stdout %}
            Windows Server 2019
          {% elif '2016' in win_version.stdout %}
            Windows Server 2016
          {% elif '2012' in win_version.stdout %}
            Windows Server 2012
          {% else %}
            Unknown version
          {% endif %}

    - name: Create report file
      win_lineinfile:
        path: "{{ report_path }}"
        line: "SERVER NAME, OS VERSION, UPTIME(Days)"
        create: yes
      delegate_to: "{{ report_server }}" 
      run_once: yes

    - name: Write consolidated report to file
      win_lineinfile:
        path: "{{ report_path }}"
        line: "{{ inventory_hostname }}, {{ windows_server_version }}, {{ server_uptime.UptimeDays }}"
      delegate_to: "{{ report_server }}"
