---
- name: Install Critical and Security Windows Updates and Ignore Failures
  hosts: all  # Replace with your target group or host
  gather_facts: no

  tasks:
    - name: Install Critical and Security Windows updates
      ansible.windows.win_updates:
        state: installed
        category_names:
          - CriticalUpdates
          - SecurityUpdates
      register: update_result
      ignore_errors: yes

    - name: Show update results
      debug:
        var: update_result
