---
- name: Check for Critical and Security Windows Updates
  hosts: all
  gather_facts: no

  tasks:
    - name: Search for Critical and Security Windows updates
      ansible.windows.win_updates:
        state: searched
        category_names:
          - CriticalUpdates
          - SecurityUpdates
      register: update_result

    - name: Show available Critical and Security updates
      debug:
        var: update_result.updates
