---
- name: Disable User Accounts and Remove Group Memberships
  ansible.windows.win_powershell:
    script: | 
      Import-Module ActiveDirectory

      function Disable-UserAccounts($userCode) {
          $suffixes = @("","_a", "_da", "_ca")
          $accountPatterns = foreach ($suffix in $suffixes) {
              $userCode + $suffix
          }
          foreach ($userName in $accountPatterns) {
              $user = Get-ADUser -Filter "SamAccountName -like '$userName'" -ErrorAction SilentlyContinue
              if ($user) {
                  Get-ADGroup -Filter * -Properties Members | Where-Object {$_.Members -like $user.DistinguishedName} | ForEach-Object{
                      Remove-ADGroupMember -Identity $_ -Members $user -Confirm:$false
                  }
                  Disable-ADAccount -Identity $user -Confirm:$false
                  Write-Host "Disabled account and removed group membership: $userName"
              }
          }
      }
      $userCode = "{{ user_code }}"  # Variable passed from Ansible
      Disable-UserAccounts -userCode $userCode
  register: offboarding_result
