---
- name: Disable User Accounts and Remove Group Memberships
  ansible.windows.win_powershell:
    script: | 
      Import-Module ActiveDirectory

      function Disable-UserAccounts($userCodesString) {
          $suffixes = "","_a", "_da", "_ca"

          $userCodes = $userCodesString -split ","

          foreach ($userCode in $userCodes) {
              $accountPatterns = $suffixes | ForEach-Object { $userCode + $_ }

              foreach ($userName in $accountPatterns) {
                  $user = Get-ADUser -Filter "SamAccountName -like '$userName'" -ErrorAction SilentlyContinue

                  if ($user) {
                      Disable-ADAccount -Identity $user -Confirm:$false

                      Get-ADGroup -Filter "Members -like '$($user.DistinguishedName)'" -Properties Members | 
                          Remove-ADGroupMember -Members $user -Confirm:$false 

                      "Disabled account and removed group membership: $userName"
                  } else {
                     "User account not found: $userName"
                  }
              }
          }
      }
      $userCodesString = "{{ user_code }}"
      Disable-UserAccounts -userCodesString $userCodesString
      "User account disabling completed."
  register: offboarding_result
  
- name: Offoarding Result
  debug:
    var: offboarding_result.output