---
- name: Get Disk Usage
  ansible.windows.win_powershell:
    script: |
      $disk = Get-WmiObject Win32_LogicalDisk -Filter "DeviceID='C:'" | Select-Object Size, FreeSpace
      $total = $disk.Size
      $free = $disk.FreeSpace
      $usage = [math]::Round((($total - $free) / $total) * 100, 2)
      $report = @{
        ServerName = $env:COMPUTERNAME
        DiskUsage = $usage
      }
      $report
  register: disk_result

- name: Display Disk Usage
  debug:
    var: disk_result.output
