---
- name: Collect C Drive Facts
  ansible.windows.win_powershell:
    script: |
      $disk = Get-WmiObject Win32_LogicalDisk -Filter "DeviceID='C:'" | Select-Object Size, FreeSpace
      $total = $disk.Size
      $free = $disk.FreeSpace
      $usage = [math]::Round((($total - $free) / $total) * 100, 2)
      $usage
  register: Dusage

- name: Display Dusage value
  debug:
    var: Dusage.stdout_lines[0]
