---
- name: Collect C Drive Facts
  ansible.windows.win_disk_facts:
    drive_letter: C
  register: disk_facts_result

- name: Save C Drive Facts to Text File
  lineinfile:
    path: C:\drive_capacity.txt
    line: "Host: {{ inventory_hostname }} | C Drive Capacity: {{ disk_facts_result.ansible_facts['ansible_devices']['c:']['size'] }}"
  delegate_to: localhost
