---
- name: Collect C Drive Facts
  ansible.windows.win_powershell:
    script: |
      $disk = Get-WmiObject Win32_LogicalDisk -Filter "DeviceID='C:'" | Select-Object Size, FreeSpace
      $total = [math]::Round($disk.Size / 1GB, 2)
      $free = [math]::Round($disk.FreeSpace / 1GB, 2)
      $usage = [math]::Round((($disk.Size - $disk.FreeSpace) / $disk.Size) * 100, 2)

      # Output the rounded variables
      @{
        total = $total
        free = $free
        usage = $usage
      }
  register: Dusage

- name: Display Dusage value
  debug:
    var: Dusage.output[0]


  