---
- name: Collect C Drive Facts
  ansible.windows.win_powershell:
    script: |
      $disk = Get-WmiObject Win32_LogicalDisk -Filter "DeviceID='C:'" | Select-Object Size, FreeSpace
      $total = $disk.Size
      $free = $disk.FreeSpace
      $usage = [math]::Round((($total - $free) / $total) * 100, 2)
      $usage
  register: Dusage

- name: Display Dusage value
  debug:
    var: Dusage.output[0]

- name: Building the temlate
  set_facts:
    report_content: "{{ report_content +[{'Host': inventory_hostname,'Usage':Dusage.output[0] }] }}"

- name: display report value
  debug:
    var: report_content

- name: Creating local File
  ansible.windows.win_template:
    src: disk_report.txt.j2
    dest: C:\disk_repo.txt
  