---
- name: Install PSWindowsUpdate Module (if needed)
  ansible.windows.win_powershell:
    script: |
      Install-Module -Name PSWindowsUpdate

- name: Find Matching Updates
  ansible.windows.win_powershell:
    script: |
      Import-Module PSWindowsUpdate

      $categories = @("Security Updates", "Critical Updates", "Definition Updates", "Update Rollups")
      $releaseMonth = {{ release_month }}
      $releaseYear = {{ release_year }}

      $updates = Get-WUList | Where-Object {
          $categories -contains $_.Category -and
          $_.Date.Month -eq $releaseMonth -and
          $_.Date.Year -eq $releaseYear
      }

      $updates | ConvertTo-Json
  register: matching_updates

- name: Download and Install Updates (No Reboot)
  ansible.windows.win_powershell:
    script: |
      Import-Module PSWindowsUpdate
      $updates = ConvertFrom-Json {{ matching_updates.stdout }}

      if ($updates) {
          Install-WUUpdates -KBArticleID $updates.KBArticleID -AcceptAll -NoReboot
      } else {
         "No updates found matching the criteria."
      }
  when: matching_updates.stdout  # Only run if updates are found

  
