---
- name: Download and install Windows updates
  ansible.windows.win_updates:
    category_names: 
      - CriticalUpdates
      - SecurityUpdates
    reboot: yes 
    reboot_timeout: 600 
  register: updates_results

- name: view
  debug:
    var: updates_results

  
