---
- name: Download and install Windows updates
  ansible.windows.win_updates:
    category_names: 
      - CriticalUpdates
      - SecurityUpdates
    reboot: no  
    #reboot_timeout: 600 

- name: Generate report of installed updates
  win_powershell:
    script: Get-Hotfix | ConvertTo-Json
  register: updates_report

- name: Save updates report to a file
  ansible.builtin.copy:
    content: "{{ updates_report.stdout }}"
    dest: windows_updates_report_{{ ansible_date_time.iso8601 }}.json

  
