---
- name: Download and install Windows updates
  ansible.windows.win_updates:
    category_names: 
      - CriticalUpdates
      - SecurityUpdates
    #reboot: yes 
    #reboot_timeout: 600 
    state: searched
  register: updates_results

- name: view
  debug:
    var: updates_results

- name: display updates found
  debug:
    msg: |
      {% for k in updates_results %}
      {{updates_results[k].title}}
      {% endfor %}
  
