---
- name: Download and install Windows updates
  ansible.windows.win_updates:
    category_names: 
      - CriticalUpdates
      - SecurityUpdates
      - UpdatesRollups
    #reboot: yes 
    #reboot_timeout: 600
    log_path: C:\ansible_upd.txt 
    state: searched
  register: updates_results

- name: view
  debug:
    var: updates_results

- name: display updates found
  debug:
    msg: |
      {% for k in updates_results.updates %}
      {{ k }}
      {% endfor %}
  
